apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-image-prod
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/devspaces-image/overlays/prod
    repoURL: https://github.com/demo-rhtssc/devspaces-image-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-devspaces-image-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
