apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: devspaces-image 
  janus-idp.io/tekton: devspaces-image
  backstage.io/kubernetes-id: devspaces-image
  backstage.io/kubernetes-namespace: rhtap-app-devspaces-image 
  app.kubernetes.io/part-of: devspaces-image
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  