apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: devspaces-image
  janus-idp.io/tekton: devspaces-image
  backstage.io/kubernetes-id: devspaces-image
  backstage.io/kubernetes-namespace: rhtap-app-devspaces-image 
  app.kubernetes.io/part-of: devspaces-image
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
