apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: devspaces-image
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devspaces-image 
  name: devspaces-image
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: devspaces-image 
